// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef _IOTSMARTCLOCK_UI_H
#define _IOTSMARTCLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen3.h"
#include "ui_mainTime.h"
#include "ui_alarmRang.h"
#include "ui_tempatureScreen.h"
#include "ui_settingsWifi.h"
#include "ui_settings.h"
#include "ui_pomodoro.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * alarmspin_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * alarmRing_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * alarmRing2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * alarmRang3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * alarmRang4_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ambientHome_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * homeFlyIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * booting_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * welcome_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1728762676);    // assets/ezgif-split/frame_00.png
LV_IMG_DECLARE(ui_img_920910679);    // assets/ezgif-split/frame_18.png
LV_IMG_DECLARE(ui_img_weather_icon_png);    // assets/weather_icon.png
LV_IMG_DECLARE(ui_img_roomtemp_png);    // assets/roomTemp.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_wifion_png);    // assets/wifiOn.png
LV_IMG_DECLARE(ui_img_powered_png);    // assets/powered.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png
LV_IMG_DECLARE(ui_img_weather_icon_2_png);    // assets/weather_icon_2.png
LV_IMG_DECLARE(ui_img_alarmicon_png);    // assets/ALARMicon.png
LV_IMG_DECLARE(ui_img_button_dissmiss_png);    // assets/BUTTON_DIssmiss.png
LV_IMG_DECLARE(ui_img_buttonsnooze_png);    // assets/buttonSnooze.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/cloudy.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_air_png);    // assets/air.png
LV_IMG_DECLARE(ui_img_1728761651);    // assets/ezgif-split/frame_01.png
LV_IMG_DECLARE(ui_img_1728760626);    // assets/ezgif-split/frame_02.png
LV_IMG_DECLARE(ui_img_1728768049);    // assets/ezgif-split/frame_03.png
LV_IMG_DECLARE(ui_img_1728758328);    // assets/ezgif-split/frame_04.png
LV_IMG_DECLARE(ui_img_1728757303);    // assets/ezgif-split/frame_05.png
LV_IMG_DECLARE(ui_img_1728756278);    // assets/ezgif-split/frame_06.png
LV_IMG_DECLARE(ui_img_1728763701);    // assets/ezgif-split/frame_07.png
LV_IMG_DECLARE(ui_img_1728771388);    // assets/ezgif-split/frame_08.png
LV_IMG_DECLARE(ui_img_1728770363);    // assets/ezgif-split/frame_09.png
LV_IMG_DECLARE(ui_img_920901967);    // assets/ezgif-split/frame_10.png
LV_IMG_DECLARE(ui_img_920900942);    // assets/ezgif-split/frame_11.png
LV_IMG_DECLARE(ui_img_920899917);    // assets/ezgif-split/frame_12.png
LV_IMG_DECLARE(ui_img_920907340);    // assets/ezgif-split/frame_13.png
LV_IMG_DECLARE(ui_img_920896594);    // assets/ezgif-split/frame_15.png
LV_IMG_DECLARE(ui_img_920895569);    // assets/ezgif-split/frame_16.png
LV_IMG_DECLARE(ui_img_920902992);    // assets/ezgif-split/frame_17.png
LV_IMG_DECLARE(ui_img_1548409061);    // assets/dark-starry-night-sky-with-black-background_1100672-16821.png

// FONTS
LV_FONT_DECLARE(ui_font_alarmBig);
LV_FONT_DECLARE(ui_font_HeadingTemp);
LV_FONT_DECLARE(ui_font_Heading_1);
LV_FONT_DECLARE(ui_font_Heading_2);
LV_FONT_DECLARE(ui_font_InterMedium);
LV_FONT_DECLARE(ui_font_InterSmall);
LV_FONT_DECLARE(ui_font_interTemp);
LV_FONT_DECLARE(ui_font_interTempHeader);
LV_FONT_DECLARE(ui_font_Setting);
LV_FONT_DECLARE(ui_font_weatherText);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
