// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_alarmSnooze;
lv_obj_t * uic_alarmDismiss;
lv_obj_t * uic_alarmTimeBig;
lv_obj_t * uic_temp;
lv_obj_t * uic_headerRight;
lv_obj_t * uic_dowDate;
lv_obj_t * uic_headerLeft;
lv_obj_t * ui_alarmRang = NULL;
lv_obj_t * ui_headerLeft = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_dowDate = NULL;
lv_obj_t * ui_headerRight = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_alarmTimeBig = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_alarmDismiss = NULL;
lv_obj_t * ui_alarmSnooze = NULL;
// event funtions
void ui_event_alarmRang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        alarmRing2_Animation(ui_Container6, 0);
        alarmRing_Animation(ui_headerRight, 0);
        alarmspin_Animation(ui_Image7, 0);
        alarmRing_Animation(ui_headerLeft, 0);
        alarmRang3_Animation(ui_Image8, 0);
        alarmRang4_Animation(ui_Label4, 0);
    }
}

void ui_event_headerLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        alarmRing_Animation(ui_headerLeft, 0);
    }
}

void ui_event_alarmDismiss(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dismissAlarmButton(e);
    }
}

// build funtions

void ui_alarmRang_screen_init(void)
{
    ui_alarmRang = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_alarmRang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_alarmRang, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_alarmRang_screen_destroy);
    lv_obj_set_style_bg_grad_color(ui_alarmRang, lv_color_hex(0x062340), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_alarmRang, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerLeft = lv_obj_create(ui_alarmRang);
    lv_obj_remove_style_all(ui_headerLeft);
    lv_obj_set_width(ui_headerLeft, lv_pct(50));
    lv_obj_set_height(ui_headerLeft, lv_pct(20));
    lv_obj_set_x(ui_headerLeft, 20);
    lv_obj_set_y(ui_headerLeft, 0);
    lv_obj_set_flex_flow(ui_headerLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_headerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_headerLeft);
    lv_img_set_src(ui_Image6, &ui_img_calendar_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 180);

    ui_dowDate = lv_label_create(ui_headerLeft);
    lv_obj_set_width(ui_dowDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dowDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dowDate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_dowDate, "Monday, January 15");
    lv_obj_set_style_text_letter_space(ui_dowDate, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dowDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_dowDate, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dowDate, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerRight = lv_obj_create(ui_alarmRang);
    lv_obj_remove_style_all(ui_headerRight);
    lv_obj_set_width(ui_headerRight, lv_pct(50));
    lv_obj_set_height(ui_headerRight, lv_pct(20));
    lv_obj_set_x(ui_headerRight, -20);
    lv_obj_set_y(ui_headerRight, 0);
    lv_obj_set_align(ui_headerRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_headerRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_headerRight, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp = lv_label_create(ui_headerRight);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_temp, "38'C Sunny");
    lv_obj_set_style_text_letter_space(ui_temp, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temp, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_headerRight);
    lv_img_set_src(ui_Image7, &ui_img_weather_icon_2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 180);

    ui_Container4 = lv_obj_create(ui_alarmRang);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(90));
    lv_obj_set_height(ui_Container4, lv_pct(60));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image8, &ui_img_alarmicon_png);
    lv_obj_set_align(ui_Image8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 150);

    ui_alarmTimeBig = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_alarmTimeBig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmTimeBig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarmTimeBig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarmTimeBig, "88:88");
    lv_obj_set_style_text_font(ui_alarmTimeBig, &ui_font_alarmBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "ALARM HIT");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x3593EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_alarmRang);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(20));
    lv_obj_set_align(ui_Container6, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmDismiss = lv_imgbtn_create(ui_Container6);
    lv_imgbtn_set_src(ui_alarmDismiss, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_dissmiss_png, NULL);
    lv_obj_set_width(ui_alarmDismiss, 169);
    lv_obj_set_height(ui_alarmDismiss, 45);
    lv_obj_set_align(ui_alarmDismiss, LV_ALIGN_LEFT_MID);

    ui_alarmSnooze = lv_imgbtn_create(ui_Container6);
    lv_imgbtn_set_src(ui_alarmSnooze, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_buttonsnooze_png, NULL);
    lv_obj_set_width(ui_alarmSnooze, 288);
    lv_obj_set_height(ui_alarmSnooze, 81);
    lv_obj_set_align(ui_alarmSnooze, LV_ALIGN_RIGHT_MID);

    lv_obj_add_event_cb(ui_headerLeft, ui_event_headerLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmDismiss, ui_event_alarmDismiss, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmRang, ui_event_alarmRang, LV_EVENT_ALL, NULL);
    uic_headerLeft = ui_headerLeft;
    uic_dowDate = ui_dowDate;
    uic_headerRight = ui_headerRight;
    uic_temp = ui_temp;
    uic_alarmTimeBig = ui_alarmTimeBig;
    uic_alarmDismiss = ui_alarmDismiss;
    uic_alarmSnooze = ui_alarmSnooze;

}

void ui_alarmRang_screen_destroy(void)
{
    if(ui_alarmRang) lv_obj_del(ui_alarmRang);

    // NULL screen variables
    ui_alarmRang = NULL;
    uic_headerLeft = NULL;
    ui_headerLeft = NULL;
    ui_Image6 = NULL;
    uic_dowDate = NULL;
    ui_dowDate = NULL;
    uic_headerRight = NULL;
    ui_headerRight = NULL;
    uic_temp = NULL;
    ui_temp = NULL;
    ui_Image7 = NULL;
    ui_Container4 = NULL;
    ui_Image8 = NULL;
    uic_alarmTimeBig = NULL;
    ui_alarmTimeBig = NULL;
    ui_Label4 = NULL;
    ui_Container6 = NULL;
    uic_alarmDismiss = NULL;
    ui_alarmDismiss = NULL;
    uic_alarmSnooze = NULL;
    ui_alarmSnooze = NULL;

}
