// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_ALARMRANG_H
#define UI_ALARMRANG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_alarmRang
extern void ui_alarmRang_screen_init(void);
extern void ui_alarmRang_screen_destroy(void);
extern lv_obj_t * ui_alarmRang;
extern lv_obj_t * ui_headerLeft;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_dowDate;
extern lv_obj_t * ui_headerRight;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_alarmTimeBig;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_alarmDismiss;
extern lv_obj_t * ui_alarmSnooze;
// CUSTOM VARIABLES
extern lv_obj_t * uic_headerLeft;
extern lv_obj_t * uic_dowDate;
extern lv_obj_t * uic_headerRight;
extern lv_obj_t * uic_temp;
extern lv_obj_t * uic_alarmTimeBig;
extern lv_obj_t * uic_alarmDismiss;
extern lv_obj_t * uic_alarmSnooze;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

