// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

// COMPONENT tempatureDisplay

lv_obj_t * ui_tempatureDisplay_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_tempatureDisplay;
    cui_tempatureDisplay = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_tempatureDisplay, 480);
    lv_obj_set_height(cui_tempatureDisplay, 320);
    lv_obj_set_align(cui_tempatureDisplay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_tempatureDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_tempatureDisplay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_tempatureDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_displayTemp;
    cui_displayTemp = lv_obj_create(cui_tempatureDisplay);
    lv_obj_set_width(cui_displayTemp, 329);
    lv_obj_set_height(cui_displayTemp, 218);
    lv_obj_set_x(cui_displayTemp, -55);
    lv_obj_set_y(cui_displayTemp, -30);
    lv_obj_set_align(cui_displayTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_displayTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_indoor;
    cui_indoor = lv_label_create(cui_displayTemp);
    lv_obj_set_width(cui_indoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_indoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_indoor, 120);
    lv_obj_set_y(cui_indoor, 80);
    lv_obj_set_align(cui_indoor, LV_ALIGN_CENTER);
    lv_label_set_text(cui_indoor, "INDOOR");
    lv_obj_set_style_text_font(cui_indoor, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tempIndoor;
    cui_tempIndoor = lv_label_create(cui_displayTemp);
    lv_obj_set_width(cui_tempIndoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_tempIndoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_tempIndoor, 101);
    lv_obj_set_y(cui_tempIndoor, 19);
    lv_obj_set_align(cui_tempIndoor, LV_ALIGN_CENTER);
    lv_label_set_text(cui_tempIndoor, "38'C");
    lv_obj_set_style_text_font(cui_tempIndoor, &ui_font_InterSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_IndoorIcon;
    cui_IndoorIcon = lv_img_create(cui_displayTemp);
    lv_obj_set_width(cui_IndoorIcon, 26);
    lv_obj_set_height(cui_IndoorIcon, 27);
    lv_obj_set_x(cui_IndoorIcon, 67);
    lv_obj_set_y(cui_IndoorIcon, 77);
    lv_obj_set_align(cui_IndoorIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_IndoorIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_IndoorIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_IndoorIcon, 400);

    lv_obj_t * cui_PanelOutdoor;
    cui_PanelOutdoor = lv_obj_create(cui_displayTemp);
    lv_obj_set_width(cui_PanelOutdoor, 199);
    lv_obj_set_height(cui_PanelOutdoor, 218);
    lv_obj_set_x(cui_PanelOutdoor, -18);
    lv_obj_set_y(cui_PanelOutdoor, 0);
    lv_obj_set_align(cui_PanelOutdoor, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(cui_PanelOutdoor, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_PanelOutdoor, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PanelOutdoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PanelOutdoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PanelOutdoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_PanelOutdoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PanelOutdoor, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_PanelOutdoor, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_outDoor;
    cui_outDoor = lv_label_create(cui_PanelOutdoor);
    lv_obj_set_width(cui_outDoor, 129);
    lv_obj_set_height(cui_outDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_outDoor, -1);
    lv_obj_set_y(cui_outDoor, -85);
    lv_obj_set_align(cui_outDoor, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(cui_outDoor, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_outDoor, "HO CHI MINH               ");
    lv_obj_set_style_text_font(cui_outDoor, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tempOutdoor;
    cui_tempOutdoor = lv_label_create(cui_PanelOutdoor);
    lv_obj_set_width(cui_tempOutdoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_tempOutdoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_tempOutdoor, 2);
    lv_obj_set_y(cui_tempOutdoor, 6);
    lv_obj_set_align(cui_tempOutdoor, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_tempOutdoor, "72'C");
    lv_obj_set_style_text_font(cui_tempOutdoor, &ui_font_InterMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_panelDayMonth;
    cui_panelDayMonth = lv_obj_create(cui_PanelOutdoor);
    lv_obj_set_width(cui_panelDayMonth, 180);
    lv_obj_set_height(cui_panelDayMonth, 29);
    lv_obj_set_x(cui_panelDayMonth, -39);
    lv_obj_set_y(cui_panelDayMonth, -55);
    lv_obj_set_align(cui_panelDayMonth, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_panelDayMonth, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_panelDayMonth, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_panelDayMonth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_panelDayMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelDayMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelDayMonth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelDayMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_decsIcon;
    cui_decsIcon = lv_img_create(cui_panelDayMonth);
    lv_obj_set_width(cui_decsIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_decsIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_decsIcon, -110);
    lv_obj_set_y(cui_decsIcon, 7);
    lv_obj_set_align(cui_decsIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_decsIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_decsIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_description;
    cui_description = lv_label_create(cui_panelDayMonth);
    lv_obj_set_width(cui_description, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_description, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_description, 12);
    lv_obj_set_y(cui_description, -300);
    lv_obj_set_align(cui_description, LV_ALIGN_CENTER);
    lv_label_set_text(cui_description, "Cloudy");
    lv_obj_set_style_text_font(cui_description, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_contHumAQI;
    cui_contHumAQI = lv_obj_create(cui_tempatureDisplay);
    lv_obj_remove_style_all(cui_contHumAQI);
    lv_obj_set_width(cui_contHumAQI, 100);
    lv_obj_set_height(cui_contHumAQI, 218);
    lv_obj_set_x(cui_contHumAQI, 171);
    lv_obj_set_y(cui_contHumAQI, -30);
    lv_obj_set_align(cui_contHumAQI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_contHumAQI, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_contHumAQI, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_contHumAQI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Hum;
    cui_Hum = lv_obj_create(cui_contHumAQI);
    lv_obj_set_width(cui_Hum, 99);
    lv_obj_set_height(cui_Hum, 86);
    lv_obj_set_x(cui_Hum, 0);
    lv_obj_set_y(cui_Hum, -66);
    lv_obj_set_align(cui_Hum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Hum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Hum, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Hum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Hum, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Hum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Hum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_percent;
    cui_percent = lv_label_create(cui_Hum);
    lv_obj_set_width(cui_percent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_percent, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_percent, "45%");
    lv_obj_set_style_text_font(cui_percent, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerHum;
    cui_headerHum = lv_label_create(cui_Hum);
    lv_obj_set_width(cui_headerHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerHum, 0);
    lv_obj_set_y(cui_headerHum, 50);
    lv_obj_set_align(cui_headerHum, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_headerHum, "HUMIDITY");
    lv_obj_set_style_text_color(cui_headerHum, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_headerHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_headerHum, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_humIcon;
    cui_humIcon = lv_img_create(cui_Hum);
    lv_obj_set_width(cui_humIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_humIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_humIcon, 0);
    lv_obj_set_y(cui_humIcon, -12);
    lv_obj_set_align(cui_humIcon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_humIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_humIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_humIcon, 390);

    lv_obj_t * cui_AQI;
    cui_AQI = lv_obj_create(cui_contHumAQI);
    lv_obj_set_width(cui_AQI, 99);
    lv_obj_set_height(cui_AQI, 86);
    lv_obj_set_x(cui_AQI, 0);
    lv_obj_set_y(cui_AQI, -66);
    lv_obj_set_align(cui_AQI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_AQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_AQI, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_AQI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_AQI, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_AQI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_AQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_AQInumber;
    cui_AQInumber = lv_label_create(cui_AQI);
    lv_obj_set_width(cui_AQInumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_AQInumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_AQInumber, 0);
    lv_obj_set_y(cui_AQInumber, 10);
    lv_obj_set_align(cui_AQInumber, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_AQInumber, "32");
    lv_obj_set_style_text_font(cui_AQInumber, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerAQI;
    cui_headerAQI = lv_label_create(cui_AQI);
    lv_obj_set_width(cui_headerAQI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerAQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerAQI, 0);
    lv_obj_set_y(cui_headerAQI, 50);
    lv_obj_set_align(cui_headerAQI, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_headerAQI, "AQI");
    lv_obj_set_style_text_color(cui_headerAQI, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_headerAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_headerAQI, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_airIcon;
    cui_airIcon = lv_img_create(cui_AQI);
    lv_obj_set_width(cui_airIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_airIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_airIcon, 0);
    lv_obj_set_y(cui_airIcon, -12);
    lv_obj_set_align(cui_airIcon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_airIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_airIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_airIcon, 330);

    lv_obj_t * cui_contAQIProperties;
    cui_contAQIProperties = lv_obj_create(cui_tempatureDisplay);
    lv_obj_remove_style_all(cui_contAQIProperties);
    lv_obj_set_width(cui_contAQIProperties, 450);
    lv_obj_set_height(cui_contAQIProperties, 50);
    lv_obj_set_x(cui_contAQIProperties, 0);
    lv_obj_set_y(cui_contAQIProperties, 120);
    lv_obj_set_align(cui_contAQIProperties, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_contAQIProperties, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_contAQIProperties, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(cui_contAQIProperties, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_panelPM25;
    cui_panelPM25 = lv_obj_create(cui_contAQIProperties);
    lv_obj_set_width(cui_panelPM25, 95);
    lv_obj_set_height(cui_panelPM25, 50);
    lv_obj_set_x(cui_panelPM25, 0);
    lv_obj_set_y(cui_panelPM25, -2);
    lv_obj_set_align(cui_panelPM25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_panelPM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panelPM25, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelPM25, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelPM25, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelPM25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerPM25;
    cui_headerPM25 = lv_label_create(cui_panelPM25);
    lv_obj_set_width(cui_headerPM25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerPM25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerPM25, 0);
    lv_obj_set_y(cui_headerPM25, -12);
    lv_obj_set_align(cui_headerPM25, LV_ALIGN_CENTER);
    lv_label_set_text(cui_headerPM25, "PM2.5");
    lv_obj_set_style_text_font(cui_headerPM25, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_headerPM25, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_headerPM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_headerPM25, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_headerPM25, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_pm25Number;
    cui_pm25Number = lv_label_create(cui_panelPM25);
    lv_obj_set_width(cui_pm25Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_pm25Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_pm25Number, 0);
    lv_obj_set_y(cui_pm25Number, 10);
    lv_obj_set_align(cui_pm25Number, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_pm25Number, "8.4 --/--");
    lv_obj_set_style_border_color(cui_pm25Number, lv_color_hex(0x077E7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_pm25Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_pm25Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_pm25Number, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_panelPM10;
    cui_panelPM10 = lv_obj_create(cui_contAQIProperties);
    lv_obj_set_width(cui_panelPM10, 95);
    lv_obj_set_height(cui_panelPM10, 50);
    lv_obj_set_x(cui_panelPM10, 0);
    lv_obj_set_y(cui_panelPM10, -2);
    lv_obj_set_align(cui_panelPM10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_panelPM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panelPM10, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelPM10, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelPM10, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelPM10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerPM10;
    cui_headerPM10 = lv_label_create(cui_panelPM10);
    lv_obj_set_width(cui_headerPM10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerPM10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerPM10, 0);
    lv_obj_set_y(cui_headerPM10, -12);
    lv_obj_set_align(cui_headerPM10, LV_ALIGN_CENTER);
    lv_label_set_text(cui_headerPM10, "PM10");
    lv_obj_set_style_text_font(cui_headerPM10, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_headerPM10, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_headerPM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_headerPM10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_headerPM10, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_pm10Number;
    cui_pm10Number = lv_label_create(cui_panelPM10);
    lv_obj_set_width(cui_pm10Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_pm10Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_pm10Number, 0);
    lv_obj_set_y(cui_pm10Number, 10);
    lv_obj_set_align(cui_pm10Number, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_pm10Number, "8.4 --/--");

    lv_obj_t * cui_panelNO;
    cui_panelNO = lv_obj_create(cui_contAQIProperties);
    lv_obj_set_width(cui_panelNO, 95);
    lv_obj_set_height(cui_panelNO, 50);
    lv_obj_set_x(cui_panelNO, 0);
    lv_obj_set_y(cui_panelNO, -2);
    lv_obj_set_align(cui_panelNO, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_panelNO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panelNO, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelNO, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelNO, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelNO, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelNO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerNO;
    cui_headerNO = lv_label_create(cui_panelNO);
    lv_obj_set_width(cui_headerNO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerNO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerNO, 0);
    lv_obj_set_y(cui_headerNO, -12);
    lv_obj_set_align(cui_headerNO, LV_ALIGN_CENTER);
    lv_label_set_text(cui_headerNO, "NO");
    lv_obj_set_style_text_font(cui_headerNO, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_headerNO, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_headerNO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_headerNO, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_headerNO, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_NONumber;
    cui_NONumber = lv_label_create(cui_panelNO);
    lv_obj_set_width(cui_NONumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_NONumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NONumber, 0);
    lv_obj_set_y(cui_NONumber, 10);
    lv_obj_set_align(cui_NONumber, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_NONumber, "8.4 --/--");

    lv_obj_t * cui_panelCO;
    cui_panelCO = lv_obj_create(cui_contAQIProperties);
    lv_obj_set_width(cui_panelCO, 95);
    lv_obj_set_height(cui_panelCO, 50);
    lv_obj_set_x(cui_panelCO, 0);
    lv_obj_set_y(cui_panelCO, -2);
    lv_obj_set_align(cui_panelCO, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_panelCO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panelCO, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelCO, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelCO, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelCO, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelCO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_headerCO;
    cui_headerCO = lv_label_create(cui_panelCO);
    lv_obj_set_width(cui_headerCO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_headerCO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_headerCO, 0);
    lv_obj_set_y(cui_headerCO, -12);
    lv_obj_set_align(cui_headerCO, LV_ALIGN_CENTER);
    lv_label_set_text(cui_headerCO, "CO");
    lv_obj_set_style_text_font(cui_headerCO, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_headerCO, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_headerCO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_headerCO, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_headerCO, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_CONumber;
    cui_CONumber = lv_label_create(cui_panelCO);
    lv_obj_set_width(cui_CONumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_CONumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_CONumber, 0);
    lv_obj_set_y(cui_CONumber, 10);
    lv_obj_set_align(cui_CONumber, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_CONumber, "8.4 --/--");

    lv_obj_t * cui_Time;
    cui_Time = lv_obj_create(cui_tempatureDisplay);
    lv_obj_set_width(cui_Time, 118);
    lv_obj_set_height(cui_Time, 72);
    lv_obj_set_x(cui_Time, 43);
    lv_obj_set_y(cui_Time, -95);
    lv_obj_set_align(cui_Time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Time, lv_color_hex(0xEDF3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Time, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dayOfWeek1;
    cui_dayOfWeek1 = lv_label_create(cui_Time);
    lv_obj_set_width(cui_dayOfWeek1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_dayOfWeek1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_dayOfWeek1, 1);
    lv_obj_set_y(cui_dayOfWeek1, -15);
    lv_obj_set_align(cui_dayOfWeek1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_dayOfWeek1, "Saturday");
    lv_obj_set_style_text_font(cui_dayOfWeek1, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_day;
    cui_day = lv_label_create(cui_Time);
    lv_obj_set_width(cui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_day, 42);
    lv_obj_set_y(cui_day, 15);
    lv_obj_set_align(cui_day, LV_ALIGN_CENTER);
    lv_label_set_text(cui_day, "14");

    lv_obj_t * cui_month;
    cui_month = lv_label_create(cui_Time);
    lv_obj_set_width(cui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_month, -14);
    lv_obj_set_y(cui_month, 15);
    lv_obj_set_align(cui_month, LV_ALIGN_CENTER);
    lv_label_set_text(cui_month, "December");

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_img_create(cui_tempatureDisplay);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(cui_Image1, -45);
    lv_obj_set_y(cui_Image1, -111);
    lv_obj_set_align(cui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_Image1, 180);
    lv_obj_set_style_img_recolor(cui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TEMPATUREDISPLAY_NUM);
    children[UI_COMP_TEMPATUREDISPLAY_TEMPATUREDISPLAY] = cui_tempatureDisplay;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP] = cui_displayTemp;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_INDOOR] = cui_indoor;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_TEMPINDOOR] = cui_tempIndoor;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_INDOORICON] = cui_IndoorIcon;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR] = cui_PanelOutdoor;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR_OUTDOOR] = cui_outDoor;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR_TEMPOUTDOOR] = cui_tempOutdoor;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR_PANELDAYMONTH] = cui_panelDayMonth;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR_PANELDAYMONTH_DECSICON] = cui_decsIcon;
    children[UI_COMP_TEMPATUREDISPLAY_DISPLAYTEMP_PANELOUTDOOR_PANELDAYMONTH_DESCRIPTION] = cui_description;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI] = cui_contHumAQI;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_HUM] = cui_Hum;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_HUM_PERCENT] = cui_percent;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_HUM_HEADERHUM] = cui_headerHum;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_HUM_HUMICON] = cui_humIcon;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_AQI] = cui_AQI;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_AQI_AQINUMBER] = cui_AQInumber;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_AQI_HEADERAQI] = cui_headerAQI;
    children[UI_COMP_TEMPATUREDISPLAY_CONTHUMAQI_AQI_AIRICON] = cui_airIcon;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES] = cui_contAQIProperties;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM25] = cui_panelPM25;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM25_HEADERPM25] = cui_headerPM25;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM25_PM25NUMBER] = cui_pm25Number;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM10] = cui_panelPM10;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM10_HEADERPM10] = cui_headerPM10;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELPM10_PM10NUMBER] = cui_pm10Number;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELNO] = cui_panelNO;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELNO_HEADERNO] = cui_headerNO;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELNO_NONUMBER] = cui_NONumber;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELCO] = cui_panelCO;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELCO_HEADERCO] = cui_headerCO;
    children[UI_COMP_TEMPATUREDISPLAY_CONTAQIPROPERTIES_PANELCO_CONUMBER] = cui_CONumber;
    children[UI_COMP_TEMPATUREDISPLAY_TIME] = cui_Time;
    children[UI_COMP_TEMPATUREDISPLAY_TIME_DAYOFWEEK1] = cui_dayOfWeek1;
    children[UI_COMP_TEMPATUREDISPLAY_TIME_DAY] = cui_day;
    children[UI_COMP_TEMPATUREDISPLAY_TIME_MONTH] = cui_month;
    children[UI_COMP_TEMPATUREDISPLAY_IMAGE1] = cui_Image1;
    lv_obj_add_event_cb(cui_tempatureDisplay, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_tempatureDisplay, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_tempatureDisplay_create_hook(cui_tempatureDisplay);
    return cui_tempatureDisplay;
}

