// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

// Forward declaration for the C++ logic function
#ifdef __cplusplus
extern "C" {
#endif
void dismissAlarm();
void snoozeAlarm();
void saveWifiSettingsC();
void loadWifiSettingsUI();
void loadSystemConfigUI();
#ifdef __cplusplus
}
#endif


void dismissAlarmButton(lv_event_t * e)
{
	// Call the actual logic in MqttService.cpp
	dismissAlarm();
}

void stop_main_animations(lv_event_t * e)
{
    if (ui_Container2) lv_anim_del(ui_Container2, NULL);
    if (ui_Container1) lv_anim_del(ui_Container1, NULL);
}

void stop_alarm_animations(lv_event_t * e)
{
    if (ui_Container6) lv_anim_del(ui_Container6, NULL);
    if (ui_headerRight) lv_anim_del(ui_headerRight, NULL);
    if (ui_Image7) lv_anim_del(ui_Image7, NULL);
    if (ui_headerLeft) lv_anim_del(ui_headerLeft, NULL);
    if (ui_Image8) lv_anim_del(ui_Image8, NULL);
    if (ui_Label4) lv_anim_del(ui_Label4, NULL);
}


void alarmSnooze(lv_event_t * e)
{
	snoozeAlarm();
}

void saveWifiSettings(lv_event_t * e)
{
	saveWifiSettingsC();
}

void loadWifiSettings(lv_event_t * e)
{
    loadWifiSettingsUI();
}

void systemConfig(lv_event_t * e)
{
	loadSystemConfigUI();
}
