// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

// Forward declaration for the C++ logic function
#ifdef __cplusplus
extern "C" {
#endif
void dismissAlarm();
#ifdef __cplusplus
}
#endif


void dismissAlarmButton(lv_event_t * e)
{
	// Call the actual logic in MqttService.cpp
	dismissAlarm();
}

