// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

// Forward declaration for the C++ logic function
#ifdef __cplusplus
extern "C" {
#endif
void dismissAlarm();
void snoozeAlarm();
#ifdef __cplusplus
}
#endif


void dismissAlarmButton(lv_event_t * e)
{
	// Call the actual logic in MqttService.cpp
	dismissAlarm();
}

void stop_main_animations(lv_event_t * e)
{
    lv_anim_del(ui_Container2, NULL);
    lv_anim_del(ui_Container1, NULL);
}

void stop_alarm_animations(lv_event_t * e)
{
    lv_anim_del(ui_Container6, NULL);
    lv_anim_del(ui_headerRight, NULL);
    lv_anim_del(ui_Image7, NULL);
    lv_anim_del(ui_headerLeft, NULL);
    lv_anim_del(ui_Image8, NULL);
    lv_anim_del(ui_Label4, NULL);
}


void alarmSnooze(lv_event_t * e)
{
	snoozeAlarm();
}
