// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void stop_main_animations(lv_event_t * e);
void stop_alarm_animations(lv_event_t * e);
void dismissAlarmButton(lv_event_t * e);
void alarmSnooze(lv_event_t * e);
void loadWifiSettings(lv_event_t * e);
void saveWifiSettings(lv_event_t * e);
void systemConfig(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
