// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_dateMonth;
lv_obj_t * uic_dayOfWeek;
lv_obj_t * uic_dateMonthPanel;
lv_obj_t * uic_seconds;
lv_obj_t * uic_hours;
lv_obj_t * uic_timePanel;
lv_obj_t * uic_indoorStatus;
lv_obj_t * uic_rtcTemp;
lv_obj_t * uic_roomTemp;
lv_obj_t * uic_weatherStatus;
lv_obj_t * uic_weatherTemp;
lv_obj_t * uic_weatherIcon;
lv_obj_t * uic_tempaturePanel;
lv_obj_t * uic_mainTime;
lv_obj_t * ui_mainTime = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_tempaturePanel = NULL;
lv_obj_t * ui_weatherIcon = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_weatherTemp = NULL;
lv_obj_t * ui_weatherStatus = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_roomTemp = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_rtcTemp = NULL;
lv_obj_t * ui_indoorStatus = NULL;
lv_obj_t * ui_timePanel = NULL;
lv_obj_t * ui_hours = NULL;
lv_obj_t * ui_seconds = NULL;
lv_obj_t * ui_dateMonthPanel = NULL;
lv_obj_t * ui_dayOfWeek = NULL;
lv_obj_t * ui_dateMonth = NULL;
// event funtions

// build funtions

void ui_mainTime_screen_init(void)
{
    ui_mainTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_mainTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainTime, lv_color_hex(0x062340), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mainTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_mainTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_mainTime, 222, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mainTime, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_mainTime);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(59));
    lv_obj_set_height(ui_Container1, lv_pct(80));
    lv_obj_set_x(ui_Container1, 18);
    lv_obj_set_y(ui_Container1, -2);
    lv_obj_set_align(ui_Container1, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempaturePanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_tempaturePanel, 283);
    lv_obj_set_height(ui_tempaturePanel, 66);
    lv_obj_set_align(ui_tempaturePanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_tempaturePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempaturePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempaturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempaturePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempaturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherIcon, 40);
    lv_obj_set_height(ui_weatherIcon, 40);
    lv_obj_set_x(ui_weatherIcon, -107);
    lv_obj_set_y(ui_weatherIcon, 0);
    lv_obj_set_align(ui_weatherIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_weatherIcon, 9999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_weatherIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_weatherIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_weatherIcon, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_weatherIcon);
    lv_image_set_src(ui_Image2, &ui_img_weather_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 105);

    ui_weatherTemp = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherTemp, 42);
    lv_obj_set_y(ui_weatherTemp, -6);
    lv_label_set_text(ui_weatherTemp, "38'C");
    lv_obj_set_style_text_font(ui_weatherTemp, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherStatus = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherStatus, 42);
    lv_obj_set_y(ui_weatherStatus, 19);
    lv_label_set_text(ui_weatherStatus, "Clear and Sunny");
    lv_obj_set_style_text_color(ui_weatherStatus, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherStatus, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_Panel5, 2);
    lv_obj_set_height(ui_Panel5, 40);
    lv_obj_set_x(ui_Panel5, 7);
    lv_obj_set_y(ui_Panel5, -2);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomTemp = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_roomTemp, 40);
    lv_obj_set_height(ui_roomTemp, 40);
    lv_obj_set_x(ui_roomTemp, 35);
    lv_obj_set_y(ui_roomTemp, 0);
    lv_obj_set_align(ui_roomTemp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_roomTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_roomTemp, 9999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_roomTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_roomTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_roomTemp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_roomTemp);
    lv_image_set_src(ui_Image3, &ui_img_roomtemp_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 105);

    ui_rtcTemp = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_rtcTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtcTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rtcTemp, 187);
    lv_obj_set_y(ui_rtcTemp, -5);
    lv_label_set_text(ui_rtcTemp, "38'C");
    lv_obj_set_style_text_font(ui_rtcTemp, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoorStatus = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_indoorStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoorStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoorStatus, 188);
    lv_obj_set_y(ui_indoorStatus, 21);
    lv_label_set_text(ui_indoorStatus, "Indoor");
    lv_obj_set_style_text_color(ui_indoorStatus, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_indoorStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_indoorStatus, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timePanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_timePanel, 276);
    lv_obj_set_height(ui_timePanel, 146);
    lv_obj_set_x(ui_timePanel, 5);
    lv_obj_set_y(ui_timePanel, -2);
    lv_obj_set_align(ui_timePanel, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_timePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hours = lv_label_create(ui_timePanel);
    lv_obj_set_width(ui_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hours, -20);
    lv_obj_set_y(ui_hours, 2);
    lv_obj_set_align(ui_hours, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_hours, "88:88");
    lv_obj_set_style_text_letter_space(ui_hours, -7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_hours, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_hours, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hours, &ui_font_InterMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seconds = lv_label_create(ui_timePanel);
    lv_obj_set_width(ui_seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seconds, 183);
    lv_obj_set_y(ui_seconds, -13);
    lv_obj_set_align(ui_seconds, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_seconds, ":88");
    lv_obj_set_style_text_color(ui_seconds, lv_color_hex(0x106ECC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_seconds, &ui_font_InterSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateMonthPanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_dateMonthPanel, 305);
    lv_obj_set_height(ui_dateMonthPanel, 63);
    lv_obj_remove_flag(ui_dateMonthPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dateMonthPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateMonthPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dateMonthPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dateMonthPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayOfWeek = lv_label_create(ui_dateMonthPanel);
    lv_obj_set_width(ui_dayOfWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayOfWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayOfWeek, -13);
    lv_obj_set_y(ui_dayOfWeek, -18);
    lv_label_set_text(ui_dayOfWeek, "WEDNESDAY");
    lv_obj_set_style_text_color(ui_dayOfWeek, lv_color_hex(0x137FEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayOfWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_dayOfWeek, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dayOfWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayOfWeek, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateMonth = lv_label_create(ui_dateMonthPanel);
    lv_obj_set_width(ui_dateMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateMonth, -16);
    lv_obj_set_y(ui_dateMonth, 10);
    lv_obj_set_align(ui_dateMonth, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_dateMonth, "October 24");
    lv_obj_set_style_text_letter_space(ui_dateMonth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dateMonth, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateMonth, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_mainTime = ui_mainTime;
    uic_tempaturePanel = ui_tempaturePanel;
    uic_weatherIcon = ui_weatherIcon;
    uic_weatherTemp = ui_weatherTemp;
    uic_weatherStatus = ui_weatherStatus;
    uic_roomTemp = ui_roomTemp;
    uic_rtcTemp = ui_rtcTemp;
    uic_indoorStatus = ui_indoorStatus;
    uic_timePanel = ui_timePanel;
    uic_hours = ui_hours;
    uic_seconds = ui_seconds;
    uic_dateMonthPanel = ui_dateMonthPanel;
    uic_dayOfWeek = ui_dayOfWeek;
    uic_dateMonth = ui_dateMonth;

}

void ui_mainTime_screen_destroy(void)
{
    if(ui_mainTime) lv_obj_del(ui_mainTime);

    // NULL screen variables
    uic_mainTime = NULL;
    ui_mainTime = NULL;
    ui_Container1 = NULL;
    uic_tempaturePanel = NULL;
    ui_tempaturePanel = NULL;
    uic_weatherIcon = NULL;
    ui_weatherIcon = NULL;
    ui_Image2 = NULL;
    uic_weatherTemp = NULL;
    ui_weatherTemp = NULL;
    uic_weatherStatus = NULL;
    ui_weatherStatus = NULL;
    ui_Panel5 = NULL;
    uic_roomTemp = NULL;
    ui_roomTemp = NULL;
    ui_Image3 = NULL;
    uic_rtcTemp = NULL;
    ui_rtcTemp = NULL;
    uic_indoorStatus = NULL;
    ui_indoorStatus = NULL;
    uic_timePanel = NULL;
    ui_timePanel = NULL;
    uic_hours = NULL;
    ui_hours = NULL;
    uic_seconds = NULL;
    ui_seconds = NULL;
    uic_dateMonthPanel = NULL;
    ui_dateMonthPanel = NULL;
    uic_dayOfWeek = NULL;
    ui_dayOfWeek = NULL;
    uic_dateMonth = NULL;
    ui_dateMonth = NULL;

}
