// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_wifiIcon;
lv_obj_t * uic_alarmTime;
lv_obj_t * uic_alarmStatus;
lv_obj_t * uic_alarm;
lv_obj_t * uic_CalendarMain;
lv_obj_t * uic_indoorStatus;
lv_obj_t * uic_rtcTemp;
lv_obj_t * uic_roomTemp;
lv_obj_t * uic_weatherStatus;
lv_obj_t * uic_weatherTemp;
lv_obj_t * uic_weatherIcon;
lv_obj_t * uic_tempaturePanel;
lv_obj_t * uic_cityName;
lv_obj_t * uic_seconds;
lv_obj_t * uic_hours;
lv_obj_t * uic_timePanel;
lv_obj_t * uic_dateMonth;
lv_obj_t * uic_dayOfWeek;
lv_obj_t * uic_dateMonthPanel;
lv_obj_t * uic_Container5;
lv_obj_t * uic_mainTime;
lv_obj_t * ui_mainTime = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_dateMonthPanel = NULL;
lv_obj_t * ui_dayOfWeek = NULL;
lv_obj_t * ui_dateMonth = NULL;
lv_obj_t * ui_timePanel = NULL;
lv_obj_t * ui_hours = NULL;
lv_obj_t * ui_seconds = NULL;
lv_obj_t * ui_cityName = NULL;
lv_obj_t * ui_tempaturePanel = NULL;
lv_obj_t * ui_weatherIcon = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_weatherTemp = NULL;
lv_obj_t * ui_weatherStatus = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_roomTemp = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_rtcTemp = NULL;
lv_obj_t * ui_indoorStatus = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_CalendarMain = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_alarmIcon = NULL;
lv_obj_t * ui_alarm = NULL;
lv_obj_t * ui_alarmStatus = NULL;
lv_obj_t * ui_alarmTime = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_wifiIcon = NULL;
lv_obj_t * ui_powerIcon = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_mainTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        homeFlyIn_Animation(ui_Container2, 0);
        ambientHome_Animation(ui_Container1, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        stop_main_animations(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_tempatureScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 400, 0, &ui_tempatureScreen_screen_init);
    }
}

// build funtions

void ui_mainTime_screen_init(void)
{
    ui_mainTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_mainTime);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x062340), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_mainTime);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(60));
    lv_obj_set_height(ui_Container1, lv_pct(85));
    lv_obj_set_align(ui_Container1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateMonthPanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_dateMonthPanel, lv_pct(100));
    lv_obj_set_height(ui_dateMonthPanel, lv_pct(25));
    lv_obj_set_x(ui_dateMonthPanel, 3);
    lv_obj_set_y(ui_dateMonthPanel, 1);
    lv_obj_set_flex_flow(ui_dateMonthPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_dateMonthPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_dateMonthPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dateMonthPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateMonthPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dateMonthPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dateMonthPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayOfWeek = lv_label_create(ui_dateMonthPanel);
    lv_obj_set_width(ui_dayOfWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayOfWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayOfWeek, -13);
    lv_obj_set_y(ui_dayOfWeek, -18);
    lv_label_set_text(ui_dayOfWeek, "STARTING");
    lv_obj_set_style_text_color(ui_dayOfWeek, lv_color_hex(0x137FEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayOfWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_dayOfWeek, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dayOfWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayOfWeek, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateMonth = lv_label_create(ui_dateMonthPanel);
    lv_obj_set_width(ui_dateMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateMonth, -16);
    lv_obj_set_y(ui_dateMonth, 10);
    lv_obj_set_align(ui_dateMonth, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_dateMonth, "PROJECT...");
    lv_obj_set_style_text_letter_space(ui_dateMonth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dateMonth, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateMonth, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timePanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_timePanel, lv_pct(100));
    lv_obj_set_height(ui_timePanel, lv_pct(50));
    lv_obj_set_x(ui_timePanel, -7);
    lv_obj_set_y(ui_timePanel, -25);
    lv_obj_set_align(ui_timePanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_timePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hours = lv_label_create(ui_timePanel);
    lv_obj_set_width(ui_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hours, -6);
    lv_obj_set_y(ui_hours, -10);
    lv_obj_set_align(ui_hours, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_hours, "00:00");
    lv_obj_set_style_text_letter_space(ui_hours, -7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_hours, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_hours, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hours, &ui_font_InterMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seconds = lv_label_create(ui_timePanel);
    lv_obj_set_width(ui_seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seconds, 183);
    lv_obj_set_y(ui_seconds, -30);
    lv_obj_set_align(ui_seconds, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_seconds, ":88");
    lv_obj_add_flag(ui_seconds, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_seconds, lv_color_hex(0x106ECC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_seconds, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_seconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_seconds, &ui_font_InterSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityName = lv_label_create(ui_timePanel);
    lv_obj_set_width(ui_cityName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cityName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityName, 0);
    lv_obj_set_y(ui_cityName, 57);
    lv_obj_set_align(ui_cityName, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_cityName, "GROUP 1's PROJECT");
    lv_obj_add_flag(ui_cityName, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_font(ui_cityName, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempaturePanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_tempaturePanel, lv_pct(100));
    lv_obj_set_height(ui_tempaturePanel, lv_pct(25));
    lv_obj_set_x(ui_tempaturePanel, -2);
    lv_obj_set_y(ui_tempaturePanel, 18);
    lv_obj_set_align(ui_tempaturePanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_tempaturePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempaturePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempaturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempaturePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempaturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherIcon = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherIcon, 40);
    lv_obj_set_height(ui_weatherIcon, 40);
    lv_obj_set_x(ui_weatherIcon, -107);
    lv_obj_set_y(ui_weatherIcon, 0);
    lv_obj_set_align(ui_weatherIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_weatherIcon, 9999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_weatherIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_weatherIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_weatherIcon, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_weatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_weatherIcon);
    lv_img_set_src(ui_Image2, &ui_img_weather_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 105);

    ui_weatherTemp = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherTemp, 42);
    lv_obj_set_y(ui_weatherTemp, -6);
    lv_label_set_text(ui_weatherTemp, "----------");
    lv_obj_set_style_text_font(ui_weatherTemp, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherStatus = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_weatherStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherStatus, 42);
    lv_obj_set_y(ui_weatherStatus, 19);
    lv_label_set_text(ui_weatherStatus, "Please Wait");
    lv_obj_set_style_text_color(ui_weatherStatus, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherStatus, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_Panel5, 2);
    lv_obj_set_height(ui_Panel5, 40);
    lv_obj_set_x(ui_Panel5, 7);
    lv_obj_set_y(ui_Panel5, -2);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomTemp = lv_obj_create(ui_tempaturePanel);
    lv_obj_set_width(ui_roomTemp, 40);
    lv_obj_set_height(ui_roomTemp, 40);
    lv_obj_set_x(ui_roomTemp, 35);
    lv_obj_set_y(ui_roomTemp, 0);
    lv_obj_set_align(ui_roomTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_roomTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_roomTemp, 9999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_roomTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_roomTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_roomTemp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_roomTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_roomTemp);
    lv_img_set_src(ui_Image3, &ui_img_roomtemp_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 105);

    ui_rtcTemp = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_rtcTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtcTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rtcTemp, 187);
    lv_obj_set_y(ui_rtcTemp, -5);
    lv_label_set_text(ui_rtcTemp, "--------");
    lv_obj_set_style_text_font(ui_rtcTemp, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoorStatus = lv_label_create(ui_tempaturePanel);
    lv_obj_set_width(ui_indoorStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoorStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoorStatus, 188);
    lv_obj_set_y(ui_indoorStatus, 21);
    lv_label_set_text(ui_indoorStatus, "Indoor Temp");
    lv_obj_set_style_text_color(ui_indoorStatus, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_indoorStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_indoorStatus, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_mainTime);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(40));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_x(ui_Container2, 200);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_set_align(ui_Container2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalendarMain = lv_calendar_create(ui_Container2);
    lv_calendar_set_today_date(ui_CalendarMain, 2025, 12, 14);
    lv_calendar_set_showed_date(ui_CalendarMain, 2025, 12);
    lv_obj_t * ui_CalendarMain_header = lv_calendar_header_arrow_create(ui_CalendarMain);
    lv_obj_set_width(ui_CalendarMain, lv_pct(100));
    lv_obj_set_height(ui_CalendarMain, lv_pct(70));
    lv_obj_set_align(ui_CalendarMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalendarMain, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_CalendarMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_CalendarMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_CalendarMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalendarMain, -15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalendarMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(20));
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -2);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmIcon = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_alarmIcon, &ui_img_alarm_png);
    lv_obj_set_width(ui_alarmIcon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_alarmIcon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_alarmIcon, -68);
    lv_obj_set_y(ui_alarmIcon, 0);
    lv_obj_set_align(ui_alarmIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarmIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_alarmIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_alarmIcon, 125);

    ui_alarm = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_alarm);
    lv_obj_set_width(ui_alarm, lv_pct(25));
    lv_obj_set_height(ui_alarm, lv_pct(100));
    lv_obj_set_x(ui_alarm, -24);
    lv_obj_set_y(ui_alarm, 0);
    lv_obj_set_align(ui_alarm, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_alarm, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_alarm, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_alarm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmStatus = lv_label_create(ui_alarm);
    lv_obj_set_width(ui_alarmStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarmStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarmStatus, "NEXT");
    lv_obj_set_style_text_color(ui_alarmStatus, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmStatus, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmTime = lv_label_create(ui_alarm);
    lv_obj_set_width(ui_alarmTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarmTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarmTime, "--:--");

    ui_Container3 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(58));
    lv_obj_set_height(ui_Container3, lv_pct(75));
    lv_obj_set_x(ui_Container3, 45);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel2, 2);
    lv_obj_set_height(ui_Panel2, 40);
    lv_obj_set_x(ui_Panel2, -10);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiIcon = lv_img_create(ui_Container3);
    lv_img_set_src(ui_wifiIcon, &ui_img_wifion_png);
    lv_obj_set_width(ui_wifiIcon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_wifiIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_wifiIcon, -28);
    lv_obj_set_y(ui_wifiIcon, 0);
    lv_obj_set_align(ui_wifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifiIcon, 115);
    lv_obj_set_style_img_recolor(ui_wifiIcon, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_wifiIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerIcon = lv_img_create(ui_Container3);
    lv_img_set_src(ui_powerIcon, &ui_img_powered_png);
    lv_obj_set_width(ui_powerIcon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_powerIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_powerIcon, 1);
    lv_obj_set_y(ui_powerIcon, 0);
    lv_obj_set_align(ui_powerIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_powerIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_powerIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_powerIcon, 115);

    ui_Label3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 55);
    lv_obj_set_y(ui_Label3, 2);
    lv_label_set_text(ui_Label3, "5V|1A");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainTime, ui_event_mainTime, LV_EVENT_ALL, NULL);
    uic_mainTime = ui_mainTime;
    uic_Container5 = ui_Container5;
    uic_dateMonthPanel = ui_dateMonthPanel;
    uic_dayOfWeek = ui_dayOfWeek;
    uic_dateMonth = ui_dateMonth;
    uic_timePanel = ui_timePanel;
    uic_hours = ui_hours;
    uic_seconds = ui_seconds;
    uic_cityName = ui_cityName;
    uic_tempaturePanel = ui_tempaturePanel;
    uic_weatherIcon = ui_weatherIcon;
    uic_weatherTemp = ui_weatherTemp;
    uic_weatherStatus = ui_weatherStatus;
    uic_roomTemp = ui_roomTemp;
    uic_rtcTemp = ui_rtcTemp;
    uic_indoorStatus = ui_indoorStatus;
    uic_CalendarMain = ui_CalendarMain;
    uic_alarm = ui_alarm;
    uic_alarmStatus = ui_alarmStatus;
    uic_alarmTime = ui_alarmTime;
    uic_wifiIcon = ui_wifiIcon;

}

void ui_mainTime_screen_destroy(void)
{
    if(ui_mainTime) lv_obj_del(ui_mainTime);

    // NULL screen variables
    uic_mainTime = NULL;
    ui_mainTime = NULL;
    uic_Container5 = NULL;
    ui_Container5 = NULL;
    ui_Container1 = NULL;
    uic_dateMonthPanel = NULL;
    ui_dateMonthPanel = NULL;
    uic_dayOfWeek = NULL;
    ui_dayOfWeek = NULL;
    uic_dateMonth = NULL;
    ui_dateMonth = NULL;
    uic_timePanel = NULL;
    ui_timePanel = NULL;
    uic_hours = NULL;
    ui_hours = NULL;
    uic_seconds = NULL;
    ui_seconds = NULL;
    uic_cityName = NULL;
    ui_cityName = NULL;
    uic_tempaturePanel = NULL;
    ui_tempaturePanel = NULL;
    uic_weatherIcon = NULL;
    ui_weatherIcon = NULL;
    ui_Image2 = NULL;
    uic_weatherTemp = NULL;
    ui_weatherTemp = NULL;
    uic_weatherStatus = NULL;
    ui_weatherStatus = NULL;
    ui_Panel5 = NULL;
    uic_roomTemp = NULL;
    ui_roomTemp = NULL;
    ui_Image3 = NULL;
    uic_rtcTemp = NULL;
    ui_rtcTemp = NULL;
    uic_indoorStatus = NULL;
    ui_indoorStatus = NULL;
    ui_Container2 = NULL;
    uic_CalendarMain = NULL;
    ui_CalendarMain = NULL;
    ui_Panel1 = NULL;
    ui_alarmIcon = NULL;
    uic_alarm = NULL;
    ui_alarm = NULL;
    uic_alarmStatus = NULL;
    ui_alarmStatus = NULL;
    uic_alarmTime = NULL;
    ui_alarmTime = NULL;
    ui_Container3 = NULL;
    ui_Panel2 = NULL;
    uic_wifiIcon = NULL;
    ui_wifiIcon = NULL;
    ui_powerIcon = NULL;
    ui_Label3 = NULL;

}
