// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAINTIME_H
#define UI_MAINTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainTime
extern void ui_mainTime_screen_init(void);
extern void ui_mainTime_screen_destroy(void);
extern lv_obj_t * ui_mainTime;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_tempaturePanel;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_weatherTemp;
extern lv_obj_t * ui_weatherStatus;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_roomTemp;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_rtcTemp;
extern lv_obj_t * ui_indoorStatus;
extern lv_obj_t * ui_timePanel;
extern lv_obj_t * ui_hours;
extern lv_obj_t * ui_seconds;
extern lv_obj_t * ui_dateMonthPanel;
extern lv_obj_t * ui_dayOfWeek;
extern lv_obj_t * ui_dateMonth;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainTime;
extern lv_obj_t * uic_tempaturePanel;
extern lv_obj_t * uic_weatherIcon;
extern lv_obj_t * uic_weatherTemp;
extern lv_obj_t * uic_weatherStatus;
extern lv_obj_t * uic_roomTemp;
extern lv_obj_t * uic_rtcTemp;
extern lv_obj_t * uic_indoorStatus;
extern lv_obj_t * uic_timePanel;
extern lv_obj_t * uic_hours;
extern lv_obj_t * uic_seconds;
extern lv_obj_t * uic_dateMonthPanel;
extern lv_obj_t * uic_dayOfWeek;
extern lv_obj_t * uic_dateMonth;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

