// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_MAINTIME_H
#define UI_MAINTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainTime
extern void ui_mainTime_screen_init(void);
extern void ui_mainTime_screen_destroy(void);
extern void ui_event_mainTime(lv_event_t * e);
extern lv_obj_t * ui_mainTime;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_dateMonthPanel;
extern lv_obj_t * ui_dayOfWeek;
extern lv_obj_t * ui_dateMonth;
extern lv_obj_t * ui_timePanel;
extern lv_obj_t * ui_hours;
extern lv_obj_t * ui_seconds;
extern lv_obj_t * ui_cityName;
extern lv_obj_t * ui_tempaturePanel;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_weatherTemp;
extern lv_obj_t * ui_weatherStatus;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_roomTemp;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_rtcTemp;
extern lv_obj_t * ui_indoorStatus;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_CalendarMain;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_alarmIcon;
extern lv_obj_t * ui_alarm;
extern lv_obj_t * ui_alarmStatus;
extern lv_obj_t * ui_alarmTime;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_wifiIcon;
extern lv_obj_t * ui_powerIcon;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainTime;
extern lv_obj_t * uic_dateMonthPanel;
extern lv_obj_t * uic_dayOfWeek;
extern lv_obj_t * uic_dateMonth;
extern lv_obj_t * uic_timePanel;
extern lv_obj_t * uic_hours;
extern lv_obj_t * uic_seconds;
extern lv_obj_t * uic_cityName;
extern lv_obj_t * uic_tempaturePanel;
extern lv_obj_t * uic_weatherIcon;
extern lv_obj_t * uic_weatherTemp;
extern lv_obj_t * uic_weatherStatus;
extern lv_obj_t * uic_roomTemp;
extern lv_obj_t * uic_rtcTemp;
extern lv_obj_t * uic_indoorStatus;
extern lv_obj_t * uic_CalendarMain;
extern lv_obj_t * uic_alarm;
extern lv_obj_t * uic_alarmStatus;
extern lv_obj_t * uic_alarmTime;
extern lv_obj_t * uic_wifiIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

