// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_POMODORO_H
#define UI_POMODORO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_pomodoro
extern void ui_pomodoro_screen_init(void);
extern void ui_pomodoro_screen_destroy(void);
extern lv_obj_t * ui_pomodoro;
extern lv_obj_t * ui_settingHeaderSmall4;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_systemTime2;
extern lv_obj_t * ui_cityNameSetting2;
extern lv_obj_t * ui_headerRight2;
extern lv_obj_t * ui_temp2;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_pomodoro;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

