// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_POMODORO_H
#define UI_POMODORO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_pomodoro
extern void ui_pomodoro_screen_init(void);
extern void ui_pomodoro_screen_destroy(void);
extern lv_obj_t * ui_pomodoro;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_settingHeaderSmall4;
extern lv_obj_t * ui_Container14;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_systemTime2;
extern lv_obj_t * ui_cityNameSetting2;
extern lv_obj_t * ui_headerRight2;
extern lv_obj_t * ui_temp2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_countDown;
extern lv_obj_t * ui_countdownTimeBig2;
extern lv_obj_t * ui_contTimer;
extern lv_obj_t * ui_timerIcon;
extern lv_obj_t * ui_headerTimer;
extern lv_obj_t * ui_SetupTime;
extern lv_obj_t * ui_PanelrollHour;
extern lv_obj_t * ui_rollHour;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_dotHour;
extern lv_obj_t * ui_PanelrollMin;
extern lv_obj_t * ui_rollMinutes;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_dotMin;
extern lv_obj_t * ui_PanelrollSecond;
extern lv_obj_t * ui_rollSeconds;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_contBtn;
extern void ui_event_btnDismiss(lv_event_t * e);
extern lv_obj_t * ui_btnDismiss;
extern lv_obj_t * ui_Label10;
extern void ui_event_btnControl(lv_event_t * e);
extern lv_obj_t * ui_btnControl;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_contBtnRUN;
extern lv_obj_t * ui_btnDismiss1;
extern lv_obj_t * ui_btnControl1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_pomodoro;
extern lv_obj_t * uic_countDown;
extern lv_obj_t * uic_contTimer;
extern lv_obj_t * uic_timerIcon;
extern lv_obj_t * uic_headerTimer;
extern lv_obj_t * uic_SetupTime;
extern lv_obj_t * uic_PanelrollHour;
extern lv_obj_t * uic_rollHour;
extern lv_obj_t * uic_hour;
extern lv_obj_t * uic_dotHour;
extern lv_obj_t * uic_PanelrollMin;
extern lv_obj_t * uic_rollMinutes;
extern lv_obj_t * uic_min;
extern lv_obj_t * uic_dotMin;
extern lv_obj_t * uic_PanelrollSecond;
extern lv_obj_t * uic_rollSeconds;
extern lv_obj_t * uic_Label9;
extern lv_obj_t * uic_btnControl;
extern lv_obj_t * uic_contBtnRUN;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

