// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_pomodoro;
lv_obj_t * ui_pomodoro = NULL;
lv_obj_t * ui_settingHeaderSmall4 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_systemTime2 = NULL;
lv_obj_t * ui_cityNameSetting2 = NULL;
lv_obj_t * ui_headerRight2 = NULL;
lv_obj_t * ui_temp2 = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions

// build funtions

void ui_pomodoro_screen_init(void)
{
    ui_pomodoro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pomodoro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pomodoro, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pomodoro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pomodoro, lv_color_hex(0x4F0566), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pomodoro, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeaderSmall4 = lv_obj_create(ui_pomodoro);
    lv_obj_remove_style_all(ui_settingHeaderSmall4);
    lv_obj_set_width(ui_settingHeaderSmall4, lv_pct(100));
    lv_obj_set_height(ui_settingHeaderSmall4, lv_pct(20));
    lv_obj_set_align(ui_settingHeaderSmall4, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_settingHeaderSmall4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingHeaderSmall4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingHeaderSmall4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container13 = lv_obj_create(ui_settingHeaderSmall4);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 100);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_systemTime2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_systemTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_systemTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemTime2, "12:30");
    lv_obj_set_style_text_font(ui_systemTime2, &ui_font_HeadingTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityNameSetting2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_cityNameSetting2, 100);
    lv_obj_set_height(ui_cityNameSetting2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityNameSetting2, 51);
    lv_obj_set_y(ui_cityNameSetting2, -2);
    lv_label_set_long_mode(ui_cityNameSetting2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_cityNameSetting2, "Ho Chi Minh");
    lv_obj_set_style_text_align(ui_cityNameSetting2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerRight2 = lv_obj_create(ui_settingHeaderSmall4);
    lv_obj_remove_style_all(ui_headerRight2);
    lv_obj_set_width(ui_headerRight2, lv_pct(50));
    lv_obj_set_height(ui_headerRight2, lv_pct(20));
    lv_obj_set_x(ui_headerRight2, -20);
    lv_obj_set_y(ui_headerRight2, 0);
    lv_obj_set_align(ui_headerRight2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_headerRight2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_headerRight2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerRight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp2 = lv_label_create(ui_headerRight2);
    lv_obj_set_width(ui_temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_temp2, "38'C Sunny");
    lv_obj_set_style_text_letter_space(ui_temp2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_temp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temp2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp2, &ui_font_Heading_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_headerRight2);
    lv_img_set_src(ui_Image11, &ui_img_weather_icon_2_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 180);

    uic_pomodoro = ui_pomodoro;

}

void ui_pomodoro_screen_destroy(void)
{
    if(ui_pomodoro) lv_obj_del(ui_pomodoro);

    // NULL screen variables
    uic_pomodoro = NULL;
    ui_pomodoro = NULL;
    ui_settingHeaderSmall4 = NULL;
    ui_Container13 = NULL;
    ui_systemTime2 = NULL;
    ui_cityNameSetting2 = NULL;
    ui_headerRight2 = NULL;
    ui_temp2 = NULL;
    ui_Image11 = NULL;

}
