// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_confirmLocation;
lv_obj_t * uic_confirmTime;
lv_obj_t * uic_setting2;
lv_obj_t * uic_setting1;
lv_obj_t * uic_cityNameSetting;
lv_obj_t * uic_systemTime;
lv_obj_t * uic_settingHeaderSmall2;
lv_obj_t * uic_settingHeaderSmall;
lv_obj_t * uic_settingHeader;
lv_obj_t * uic_settings;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_settingHeader = NULL;
lv_obj_t * ui_settingHeaderSmall = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_settingHeaderSmall2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_systemTime = NULL;
lv_obj_t * ui_cityNameSetting = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_setting1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Checkbox1 = NULL;
lv_obj_t * ui_setting2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_setting3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_setting4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_setting5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_confirmTime = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_confirmLocation = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_mainTime, LV_SCR_LOAD_ANIM_OUT_TOP, 400, 0, &ui_mainTime_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsWifi, LV_SCR_LOAD_ANIM_FADE_ON, 400, 5, &ui_settingsWifi_screen_init);
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BlueBG);
    ui_object_set_themeable_style_property(ui_settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_settings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeader = lv_obj_create(ui_settings);
    lv_obj_remove_style_all(ui_settingHeader);
    lv_obj_set_width(ui_settingHeader, lv_pct(100));
    lv_obj_set_height(ui_settingHeader, lv_pct(20));
    lv_obj_set_align(ui_settingHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_settingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingHeader, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingHeader, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeaderSmall = lv_obj_create(ui_settingHeader);
    lv_obj_remove_style_all(ui_settingHeaderSmall);
    lv_obj_set_width(ui_settingHeaderSmall, lv_pct(60));
    lv_obj_set_height(ui_settingHeaderSmall, lv_pct(100));
    lv_obj_set_flex_flow(ui_settingHeaderSmall, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingHeaderSmall, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingHeaderSmall, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_settingHeaderSmall);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "System Settings");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeaderSmall2 = lv_obj_create(ui_settingHeader);
    lv_obj_remove_style_all(ui_settingHeaderSmall2);
    lv_obj_set_width(ui_settingHeaderSmall2, lv_pct(40));
    lv_obj_set_height(ui_settingHeaderSmall2, lv_pct(100));
    lv_obj_set_align(ui_settingHeaderSmall2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_settingHeaderSmall2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingHeaderSmall2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingHeaderSmall2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_settingHeaderSmall2);
    lv_img_set_src(ui_Image1, &ui_img_alarm_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 150);

    ui_Container9 = lv_obj_create(ui_settingHeaderSmall2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 100);
    lv_obj_set_height(ui_Container9, 50);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_systemTime = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_systemTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_systemTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemTime, "12:30");
    lv_obj_set_style_text_font(ui_systemTime, &ui_font_HeadingTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityNameSetting = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_cityNameSetting, 94);
    lv_obj_set_height(ui_cityNameSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityNameSetting, 51);
    lv_obj_set_y(ui_cityNameSetting, -2);
    lv_label_set_long_mode(ui_cityNameSetting, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_cityNameSetting, "Ho Chi Minh");

    ui_Container11 = lv_obj_create(ui_settings);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, lv_pct(100));
    lv_obj_set_height(ui_Container11, lv_pct(80));
    lv_obj_set_align(ui_Container11, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting1 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_setting1, lv_pct(90));
    lv_obj_set_height(ui_setting1, lv_pct(18));
    lv_obj_set_x(ui_setting1, 54);
    lv_obj_set_y(ui_setting1, 1);
    lv_obj_set_align(ui_setting1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting1, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_setting1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Brightness");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_setting1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, lv_pct(38));
    lv_obj_set_height(ui_Slider1, lv_pct(70));
    lv_obj_set_x(ui_Slider1, 31);
    lv_obj_set_y(ui_Slider1, 23);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Checkbox1 = lv_checkbox_create(ui_setting1);
    lv_checkbox_set_text(ui_Checkbox1, "Auto");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_setting2 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_setting2, lv_pct(90));
    lv_obj_set_height(ui_setting2, lv_pct(18));
    lv_obj_set_x(ui_setting2, 54);
    lv_obj_set_y(ui_setting2, 1);
    lv_obj_set_align(ui_setting2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting2, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_setting2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Timezone");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_setting2);
    lv_roller_set_options(ui_Roller1, "UTC +5\nUTC +6\nUTC +7 Vietnam", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 30);
    lv_obj_set_width(ui_Roller1, lv_pct(45));
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_Roller1, 20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BlueBG);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BlueBG);

    ui_setting3 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_setting3, lv_pct(90));
    lv_obj_set_height(ui_setting3, lv_pct(18));
    lv_obj_set_x(ui_setting3, 54);
    lv_obj_set_y(ui_setting3, 1);
    lv_obj_set_align(ui_setting3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting3, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_setting3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Location");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_setting3);
    lv_dropdown_set_options(ui_Dropdown1, "Da Lat\nHa Noi\nHo Chi Minh");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_Dropdown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BlueBG);
    ui_object_set_themeable_style_property(ui_Dropdown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BlueBG);

    ui_setting4 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_setting4, lv_pct(90));
    lv_obj_set_height(ui_setting4, lv_pct(18));
    lv_obj_set_x(ui_setting4, 54);
    lv_obj_set_y(ui_setting4, 1);
    lv_obj_set_align(ui_setting4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting4, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_setting4);
    lv_obj_set_height(ui_Button2, 34);
    lv_obj_set_width(ui_Button2, lv_pct(106));
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label7, lv_pct(100));
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Wifi Settings");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting5 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_setting5, lv_pct(90));
    lv_obj_set_height(ui_setting5, lv_pct(18));
    lv_obj_set_x(ui_setting5, 54);
    lv_obj_set_y(ui_setting5, 1);
    lv_obj_set_align(ui_setting5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting5, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_setting5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Confirm");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmTime = lv_btn_create(ui_setting5);
    lv_obj_set_width(ui_confirmTime, 130);
    lv_obj_set_height(ui_confirmTime, 30);
    lv_obj_set_align(ui_confirmTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confirmTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_confirmTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_confirmTime, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_confirmTime);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Update Time");

    ui_Label11 = lv_label_create(ui_confirmTime);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Update Time");

    ui_confirmLocation = lv_btn_create(ui_setting5);
    lv_obj_set_width(ui_confirmLocation, 130);
    lv_obj_set_height(ui_confirmLocation, 30);
    lv_obj_set_align(ui_confirmLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmLocation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confirmLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_confirmLocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_confirmLocation, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_confirmLocation);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Update Location");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    uic_settings = ui_settings;
    uic_settingHeader = ui_settingHeader;
    uic_settingHeaderSmall = ui_settingHeaderSmall;
    uic_settingHeaderSmall2 = ui_settingHeaderSmall2;
    uic_systemTime = ui_systemTime;
    uic_cityNameSetting = ui_cityNameSetting;
    uic_setting1 = ui_setting1;
    uic_setting2 = ui_setting2;
    uic_confirmTime = ui_confirmTime;
    uic_confirmLocation = ui_confirmLocation;

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    uic_settings = NULL;
    ui_settings = NULL;
    uic_settingHeader = NULL;
    ui_settingHeader = NULL;
    uic_settingHeaderSmall = NULL;
    ui_settingHeaderSmall = NULL;
    ui_Label1 = NULL;
    uic_settingHeaderSmall2 = NULL;
    ui_settingHeaderSmall2 = NULL;
    ui_Image1 = NULL;
    ui_Container9 = NULL;
    uic_systemTime = NULL;
    ui_systemTime = NULL;
    uic_cityNameSetting = NULL;
    ui_cityNameSetting = NULL;
    ui_Container11 = NULL;
    uic_setting1 = NULL;
    ui_setting1 = NULL;
    ui_Label5 = NULL;
    ui_Slider1 = NULL;
    ui_Checkbox1 = NULL;
    uic_setting2 = NULL;
    ui_setting2 = NULL;
    ui_Label2 = NULL;
    ui_Roller1 = NULL;
    ui_setting3 = NULL;
    ui_Label6 = NULL;
    ui_Dropdown1 = NULL;
    ui_setting4 = NULL;
    ui_Button2 = NULL;
    ui_Label7 = NULL;
    ui_setting5 = NULL;
    ui_Label8 = NULL;
    uic_confirmTime = NULL;
    ui_confirmTime = NULL;
    ui_Label9 = NULL;
    ui_Label11 = NULL;
    uic_confirmLocation = NULL;
    ui_confirmLocation = NULL;
    ui_Label10 = NULL;

}
