// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_Keyboardssid;
lv_obj_t * uic_ssidPwd;
lv_obj_t * uic_ssid;
lv_obj_t * uic_settingsWifi;
lv_obj_t * ui_settingsWifi = NULL;
lv_obj_t * ui_settingHeader1 = NULL;
lv_obj_t * ui_settingHeaderSmall1 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_setting7 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_ssid = NULL;
lv_obj_t * ui_setting8 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_ssidPwd = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_setting9 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Keyboardssid = NULL;
// event funtions
void ui_event_ssid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboardssid,  ui_ssid);
        _ui_flag_modify(ui_Keyboardssid, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ssidPwd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboardssid,  ui_ssidPwd);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_FADE_ON, 400, 5, &ui_settings_screen_init);
    }
}

void ui_event_Keyboardssid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboardssid, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// build funtions

void ui_settingsWifi_screen_init(void)
{
    ui_settingsWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_settingsWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BlueBG);
    ui_object_set_themeable_style_property(ui_settingsWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_settingsWifi, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeader1 = lv_obj_create(ui_settingsWifi);
    lv_obj_remove_style_all(ui_settingHeader1);
    lv_obj_set_width(ui_settingHeader1, lv_pct(100));
    lv_obj_set_height(ui_settingHeader1, lv_pct(20));
    lv_obj_set_align(ui_settingHeader1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_settingHeader1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingHeader1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingHeader1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingHeader1, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingHeaderSmall1 = lv_obj_create(ui_settingHeader1);
    lv_obj_remove_style_all(ui_settingHeaderSmall1);
    lv_obj_set_width(ui_settingHeaderSmall1, lv_pct(100));
    lv_obj_set_height(ui_settingHeaderSmall1, lv_pct(100));
    lv_obj_set_flex_flow(ui_settingHeaderSmall1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingHeaderSmall1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingHeaderSmall1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_settingHeaderSmall1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Wifi Configuration");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_settingsWifi);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(50));
    lv_obj_set_x(ui_Container8, 0);
    lv_obj_set_y(ui_Container8, lv_pct(20));
    lv_obj_set_align(ui_Container8, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting7 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_setting7, lv_pct(90));
    lv_obj_set_height(ui_setting7, lv_pct(25));
    lv_obj_set_x(ui_setting7, 54);
    lv_obj_set_y(ui_setting7, 1);
    lv_obj_set_align(ui_setting7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting7, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_setting7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "SSID");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssid = lv_textarea_create(ui_setting7);
    lv_obj_set_width(ui_ssid, 200);
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_ssid, 22);
    lv_obj_set_y(ui_ssid, -2);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ssid, "Bluevolt_2.4");
    lv_textarea_set_placeholder_text(ui_ssid, "Placeholder...");
    lv_textarea_set_one_line(ui_ssid, true);
    ui_object_set_themeable_style_property(ui_ssid, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_ssid, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting8 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_setting8, lv_pct(90));
    lv_obj_set_height(ui_setting8, lv_pct(25));
    lv_obj_set_x(ui_setting8, 54);
    lv_obj_set_y(ui_setting8, 1);
    lv_obj_set_align(ui_setting8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting8, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_setting8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Password");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidPwd = lv_textarea_create(ui_setting8);
    lv_obj_set_width(ui_ssidPwd, 200);
    lv_obj_set_height(ui_ssidPwd, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_ssidPwd, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ssidPwd, "0877884747");
    lv_textarea_set_placeholder_text(ui_ssidPwd, "Placeholder...");
    lv_textarea_set_one_line(ui_ssidPwd, true);
    lv_textarea_set_password_mode(ui_ssidPwd, true);
    ui_object_set_themeable_style_property(ui_ssidPwd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BlueBG);
    lv_obj_set_style_bg_grad_dir(ui_ssidPwd, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_settingsWifi);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_height(ui_Container10, 50);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_align(ui_Container10, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting9 = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_setting9, lv_pct(100));
    lv_obj_set_height(ui_setting9, lv_pct(100));
    lv_obj_set_align(ui_setting9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setting9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setting9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting9, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_setting9);
    lv_obj_set_height(ui_Button1, 34);
    lv_obj_set_width(ui_Button1, lv_pct(106));
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label16, lv_pct(100));
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Save and Connect");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Setting, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboardssid = lv_keyboard_create(ui_settingsWifi);
    lv_obj_set_width(ui_Keyboardssid, lv_pct(90));
    lv_obj_set_height(ui_Keyboardssid, lv_pct(40));
    lv_obj_set_align(ui_Keyboardssid, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboardssid, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ssid, ui_event_ssid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ssidPwd, ui_event_ssidPwd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboardssid, ui_ssid);
    lv_obj_add_event_cb(ui_Keyboardssid, ui_event_Keyboardssid, LV_EVENT_ALL, NULL);
    uic_settingsWifi = ui_settingsWifi;
    uic_ssid = ui_ssid;
    uic_ssidPwd = ui_ssidPwd;
    uic_Keyboardssid = ui_Keyboardssid;

}

void ui_settingsWifi_screen_destroy(void)
{
    if(ui_settingsWifi) lv_obj_del(ui_settingsWifi);

    // NULL screen variables
    uic_settingsWifi = NULL;
    ui_settingsWifi = NULL;
    ui_settingHeader1 = NULL;
    ui_settingHeaderSmall1 = NULL;
    ui_Label12 = NULL;
    ui_Container8 = NULL;
    ui_setting7 = NULL;
    ui_Label14 = NULL;
    uic_ssid = NULL;
    ui_ssid = NULL;
    ui_setting8 = NULL;
    ui_Label15 = NULL;
    uic_ssidPwd = NULL;
    ui_ssidPwd = NULL;
    ui_Container10 = NULL;
    ui_setting9 = NULL;
    ui_Button1 = NULL;
    ui_Label16 = NULL;
    uic_Keyboardssid = NULL;
    ui_Keyboardssid = NULL;

}
