// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_settingHeader;
extern lv_obj_t * ui_settingHeaderSmall;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_settingHeaderSmall2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_systemTime;
extern lv_obj_t * ui_cityNameSetting;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_setting1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_setting2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_setting3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_setting4;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_setting5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_confirmTime;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_confirmLocation;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settings;
extern lv_obj_t * uic_settingHeader;
extern lv_obj_t * uic_settingHeaderSmall;
extern lv_obj_t * uic_settingHeaderSmall2;
extern lv_obj_t * uic_systemTime;
extern lv_obj_t * uic_cityNameSetting;
extern lv_obj_t * uic_setting1;
extern lv_obj_t * uic_setting2;
extern lv_obj_t * uic_confirmTime;
extern lv_obj_t * uic_confirmLocation;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

