// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#include "ui.h"

lv_obj_t * uic_day1;
lv_obj_t * uic_dayOfWeek2;
lv_obj_t * uic_CONumber1;
lv_obj_t * uic_headerCO1;
lv_obj_t * uic_NONumber1;
lv_obj_t * uic_headerNO1;
lv_obj_t * uic_pm10Number1;
lv_obj_t * uic_headerPM10;
lv_obj_t * uic_pm25Number1;
lv_obj_t * uic_headerPM25;
lv_obj_t * uic_AQInumber1;
lv_obj_t * uic_percent1;
lv_obj_t * uic_description1;
lv_obj_t * uic_tempOutdoor1;
lv_obj_t * uic_cityNameTemp;
lv_obj_t * uic_tempIndoor1;
lv_obj_t * uic_tempatureScreen;
lv_obj_t * ui_tempatureScreen = NULL;
lv_obj_t * ui_tempatureDisplay2 = NULL;
lv_obj_t * ui_displayTemp1 = NULL;
lv_obj_t * ui_indoor1 = NULL;
lv_obj_t * ui_tempIndoor1 = NULL;
lv_obj_t * ui_IndoorIcon1 = NULL;
lv_obj_t * ui_PanelOutdoor1 = NULL;
lv_obj_t * ui_cityNameTemp = NULL;
lv_obj_t * ui_tempOutdoor1 = NULL;
lv_obj_t * ui_panelDayMonth1 = NULL;
lv_obj_t * ui_decsIcon1 = NULL;
lv_obj_t * ui_description1 = NULL;
lv_obj_t * ui_contHumAQI1 = NULL;
lv_obj_t * ui_Hum1 = NULL;
lv_obj_t * ui_percent1 = NULL;
lv_obj_t * ui_headerHum1 = NULL;
lv_obj_t * ui_humIcon1 = NULL;
lv_obj_t * ui_AQI1 = NULL;
lv_obj_t * ui_AQInumber1 = NULL;
lv_obj_t * ui_headerAQI1 = NULL;
lv_obj_t * ui_airIcon1 = NULL;
lv_obj_t * ui_contAQIProperties1 = NULL;
lv_obj_t * ui_panelPM1 = NULL;
lv_obj_t * ui_headerPM25 = NULL;
lv_obj_t * ui_pm25Number1 = NULL;
lv_obj_t * ui_panelPM2 = NULL;
lv_obj_t * ui_headerPM10 = NULL;
lv_obj_t * ui_pm10Number1 = NULL;
lv_obj_t * ui_panelNO1 = NULL;
lv_obj_t * ui_headerNO1 = NULL;
lv_obj_t * ui_NONumber1 = NULL;
lv_obj_t * ui_panelCO1 = NULL;
lv_obj_t * ui_headerCO1 = NULL;
lv_obj_t * ui_CONumber1 = NULL;
lv_obj_t * ui_Time1 = NULL;
lv_obj_t * ui_dayOfWeek2 = NULL;
lv_obj_t * ui_day1 = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions
void ui_event_tempatureScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_mainTime, LV_SCR_LOAD_ANIM_OVER_LEFT, 400, 0, &ui_mainTime_screen_init);
    }
}

// build funtions

void ui_tempatureScreen_screen_init(void)
{
    ui_tempatureScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tempatureScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempatureDisplay2 = lv_obj_create(ui_tempatureScreen);
    lv_obj_set_width(ui_tempatureDisplay2, 480);
    lv_obj_set_height(ui_tempatureDisplay2, 320);
    lv_obj_set_align(ui_tempatureDisplay2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempatureDisplay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempatureDisplay2, lv_color_hex(0x062340), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempatureDisplay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_tempatureDisplay2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_displayTemp1 = lv_obj_create(ui_tempatureDisplay2);
    lv_obj_set_width(ui_displayTemp1, 329);
    lv_obj_set_height(ui_displayTemp1, 218);
    lv_obj_set_x(ui_displayTemp1, -55);
    lv_obj_set_y(ui_displayTemp1, -30);
    lv_obj_set_align(ui_displayTemp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_displayTemp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_displayTemp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_displayTemp1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_displayTemp1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_displayTemp1, &ui_img_1548409061, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_displayTemp1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_displayTemp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_displayTemp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor1 = lv_label_create(ui_displayTemp1);
    lv_obj_set_width(ui_indoor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor1, 120);
    lv_obj_set_y(ui_indoor1, 80);
    lv_obj_set_align(ui_indoor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_indoor1, "INDOOR");
    lv_obj_set_style_text_font(ui_indoor1, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempIndoor1 = lv_label_create(ui_displayTemp1);
    lv_obj_set_width(ui_tempIndoor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempIndoor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempIndoor1, 101);
    lv_obj_set_y(ui_tempIndoor1, 19);
    lv_obj_set_align(ui_tempIndoor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempIndoor1, "38'C");
    lv_obj_set_style_text_color(ui_tempIndoor1, lv_color_hex(0x1BD150), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempIndoor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_tempIndoor1, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_tempIndoor1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempIndoor1, &ui_font_InterSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IndoorIcon1 = lv_img_create(ui_displayTemp1);
    lv_img_set_src(ui_IndoorIcon1, &ui_img_home_png);
    lv_obj_set_width(ui_IndoorIcon1, 26);
    lv_obj_set_height(ui_IndoorIcon1, 27);
    lv_obj_set_x(ui_IndoorIcon1, 67);
    lv_obj_set_y(ui_IndoorIcon1, 77);
    lv_obj_set_align(ui_IndoorIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IndoorIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IndoorIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IndoorIcon1, 400);

    ui_PanelOutdoor1 = lv_obj_create(ui_displayTemp1);
    lv_obj_set_width(ui_PanelOutdoor1, 199);
    lv_obj_set_height(ui_PanelOutdoor1, 218);
    lv_obj_set_x(ui_PanelOutdoor1, -18);
    lv_obj_set_y(ui_PanelOutdoor1, 0);
    lv_obj_set_align(ui_PanelOutdoor1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_PanelOutdoor1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelOutdoor1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelOutdoor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelOutdoor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOutdoor1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelOutdoor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelOutdoor1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelOutdoor1, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityNameTemp = lv_label_create(ui_PanelOutdoor1);
    lv_obj_set_width(ui_cityNameTemp, 129);
    lv_obj_set_height(ui_cityNameTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityNameTemp, -1);
    lv_obj_set_y(ui_cityNameTemp, -85);
    lv_obj_set_align(ui_cityNameTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_cityNameTemp, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_cityNameTemp, "HO CHI MINH               ");
    lv_obj_set_style_text_font(ui_cityNameTemp, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOutdoor1 = lv_label_create(ui_PanelOutdoor1);
    lv_obj_set_width(ui_tempOutdoor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempOutdoor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempOutdoor1, 2);
    lv_obj_set_y(ui_tempOutdoor1, 6);
    lv_obj_set_align(ui_tempOutdoor1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_tempOutdoor1, "37'C");
    lv_obj_set_style_text_letter_space(ui_tempOutdoor1, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_tempOutdoor1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempOutdoor1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempOutdoor1, &ui_font_alarmBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelDayMonth1 = lv_obj_create(ui_PanelOutdoor1);
    lv_obj_set_width(ui_panelDayMonth1, 180);
    lv_obj_set_height(ui_panelDayMonth1, 29);
    lv_obj_set_x(ui_panelDayMonth1, -39);
    lv_obj_set_y(ui_panelDayMonth1, -55);
    lv_obj_set_align(ui_panelDayMonth1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelDayMonth1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelDayMonth1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelDayMonth1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelDayMonth1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelDayMonth1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelDayMonth1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelDayMonth1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_decsIcon1 = lv_img_create(ui_panelDayMonth1);
    lv_img_set_src(ui_decsIcon1, &ui_img_cloudy_png);
    lv_obj_set_width(ui_decsIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_decsIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_decsIcon1, -110);
    lv_obj_set_y(ui_decsIcon1, 7);
    lv_obj_set_align(ui_decsIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_decsIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_decsIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_description1 = lv_label_create(ui_panelDayMonth1);
    lv_obj_set_width(ui_description1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_description1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_description1, 12);
    lv_obj_set_y(ui_description1, -300);
    lv_obj_set_align(ui_description1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_description1, "Cloudy");
    lv_obj_set_style_text_font(ui_description1, &ui_font_interTemp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHumAQI1 = lv_obj_create(ui_tempatureDisplay2);
    lv_obj_remove_style_all(ui_contHumAQI1);
    lv_obj_set_width(ui_contHumAQI1, 100);
    lv_obj_set_height(ui_contHumAQI1, 218);
    lv_obj_set_x(ui_contHumAQI1, 171);
    lv_obj_set_y(ui_contHumAQI1, -30);
    lv_obj_set_align(ui_contHumAQI1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHumAQI1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contHumAQI1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_contHumAQI1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hum1 = lv_obj_create(ui_contHumAQI1);
    lv_obj_set_width(ui_Hum1, 99);
    lv_obj_set_height(ui_Hum1, 86);
    lv_obj_set_x(ui_Hum1, 0);
    lv_obj_set_y(ui_Hum1, -66);
    lv_obj_set_align(ui_Hum1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Hum1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Hum1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Hum1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hum1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Hum1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Hum1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent1 = lv_label_create(ui_Hum1);
    lv_obj_set_width(ui_percent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_percent1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_percent1, "45%");
    lv_obj_set_style_text_align(ui_percent1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percent1, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_percent1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_percent1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_percent1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_percent1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerHum1 = lv_label_create(ui_Hum1);
    lv_obj_set_width(ui_headerHum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerHum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerHum1, 0);
    lv_obj_set_y(ui_headerHum1, 50);
    lv_obj_set_align(ui_headerHum1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_headerHum1, "HUMIDITY");
    lv_obj_set_style_text_color(ui_headerHum1, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_headerHum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_headerHum1, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humIcon1 = lv_img_create(ui_Hum1);
    lv_img_set_src(ui_humIcon1, &ui_img_humidity_png);
    lv_obj_set_width(ui_humIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humIcon1, 0);
    lv_obj_set_y(ui_humIcon1, -12);
    lv_obj_set_align(ui_humIcon1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_humIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humIcon1, 390);

    ui_AQI1 = lv_obj_create(ui_contHumAQI1);
    lv_obj_set_width(ui_AQI1, 99);
    lv_obj_set_height(ui_AQI1, 86);
    lv_obj_set_x(ui_AQI1, 0);
    lv_obj_set_y(ui_AQI1, -66);
    lv_obj_set_align(ui_AQI1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AQI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AQI1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AQI1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AQI1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AQI1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AQI1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQInumber1 = lv_label_create(ui_AQI1);
    lv_obj_set_width(ui_AQInumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQInumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQInumber1, 0);
    lv_obj_set_y(ui_AQInumber1, 10);
    lv_obj_set_align(ui_AQInumber1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AQInumber1, "32");
    lv_obj_set_style_text_font(ui_AQInumber1, &ui_font_Heading_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerAQI1 = lv_label_create(ui_AQI1);
    lv_obj_set_width(ui_headerAQI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerAQI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerAQI1, 0);
    lv_obj_set_y(ui_headerAQI1, 50);
    lv_obj_set_align(ui_headerAQI1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_headerAQI1, "AQI");
    lv_obj_set_style_text_color(ui_headerAQI1, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_headerAQI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_headerAQI1, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airIcon1 = lv_img_create(ui_AQI1);
    lv_img_set_src(ui_airIcon1, &ui_img_air_png);
    lv_obj_set_width(ui_airIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airIcon1, 0);
    lv_obj_set_y(ui_airIcon1, -12);
    lv_obj_set_align(ui_airIcon1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_airIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_airIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_airIcon1, 330);

    ui_contAQIProperties1 = lv_obj_create(ui_tempatureDisplay2);
    lv_obj_remove_style_all(ui_contAQIProperties1);
    lv_obj_set_width(ui_contAQIProperties1, 450);
    lv_obj_set_height(ui_contAQIProperties1, 50);
    lv_obj_set_x(ui_contAQIProperties1, 0);
    lv_obj_set_y(ui_contAQIProperties1, 120);
    lv_obj_set_align(ui_contAQIProperties1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contAQIProperties1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contAQIProperties1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_contAQIProperties1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelPM1 = lv_obj_create(ui_contAQIProperties1);
    lv_obj_set_width(ui_panelPM1, 95);
    lv_obj_set_height(ui_panelPM1, 50);
    lv_obj_set_x(ui_panelPM1, 0);
    lv_obj_set_y(ui_panelPM1, -2);
    lv_obj_set_align(ui_panelPM1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelPM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelPM1, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelPM1, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelPM1, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelPM1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerPM25 = lv_label_create(ui_panelPM1);
    lv_obj_set_width(ui_headerPM25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerPM25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerPM25, 0);
    lv_obj_set_y(ui_headerPM25, -12);
    lv_obj_set_align(ui_headerPM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_headerPM25, "PM2.5");
    lv_obj_set_style_text_font(ui_headerPM25, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_headerPM25, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerPM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerPM25, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_headerPM25, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Number1 = lv_label_create(ui_panelPM1);
    lv_obj_set_width(ui_pm25Number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25Number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25Number1, 0);
    lv_obj_set_y(ui_pm25Number1, 10);
    lv_obj_set_align(ui_pm25Number1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_pm25Number1, "8.4 --/--");
    lv_obj_set_style_border_color(ui_pm25Number1, lv_color_hex(0x077E7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm25Number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm25Number1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pm25Number1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelPM2 = lv_obj_create(ui_contAQIProperties1);
    lv_obj_set_width(ui_panelPM2, 95);
    lv_obj_set_height(ui_panelPM2, 50);
    lv_obj_set_x(ui_panelPM2, 0);
    lv_obj_set_y(ui_panelPM2, -2);
    lv_obj_set_align(ui_panelPM2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelPM2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelPM2, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelPM2, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelPM2, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelPM2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelPM2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerPM10 = lv_label_create(ui_panelPM2);
    lv_obj_set_width(ui_headerPM10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerPM10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerPM10, 0);
    lv_obj_set_y(ui_headerPM10, -12);
    lv_obj_set_align(ui_headerPM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_headerPM10, "PM10");
    lv_obj_set_style_text_font(ui_headerPM10, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_headerPM10, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerPM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerPM10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_headerPM10, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Number1 = lv_label_create(ui_panelPM2);
    lv_obj_set_width(ui_pm10Number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10Number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10Number1, 0);
    lv_obj_set_y(ui_pm10Number1, 10);
    lv_obj_set_align(ui_pm10Number1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_pm10Number1, "8.4 --/--");

    ui_panelNO1 = lv_obj_create(ui_contAQIProperties1);
    lv_obj_set_width(ui_panelNO1, 95);
    lv_obj_set_height(ui_panelNO1, 50);
    lv_obj_set_x(ui_panelNO1, 0);
    lv_obj_set_y(ui_panelNO1, -2);
    lv_obj_set_align(ui_panelNO1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelNO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelNO1, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelNO1, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelNO1, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelNO1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelNO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerNO1 = lv_label_create(ui_panelNO1);
    lv_obj_set_width(ui_headerNO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerNO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerNO1, 0);
    lv_obj_set_y(ui_headerNO1, -12);
    lv_obj_set_align(ui_headerNO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_headerNO1, "NO");
    lv_obj_set_style_text_font(ui_headerNO1, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_headerNO1, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerNO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerNO1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_headerNO1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NONumber1 = lv_label_create(ui_panelNO1);
    lv_obj_set_width(ui_NONumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NONumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NONumber1, 0);
    lv_obj_set_y(ui_NONumber1, 10);
    lv_obj_set_align(ui_NONumber1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_NONumber1, "8.4 --/--");

    ui_panelCO1 = lv_obj_create(ui_contAQIProperties1);
    lv_obj_set_width(ui_panelCO1, 95);
    lv_obj_set_height(ui_panelCO1, 50);
    lv_obj_set_x(ui_panelCO1, 0);
    lv_obj_set_y(ui_panelCO1, -2);
    lv_obj_set_align(ui_panelCO1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelCO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelCO1, 99999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelCO1, lv_color_hex(0x183A8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelCO1, 83, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelCO1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelCO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerCO1 = lv_label_create(ui_panelCO1);
    lv_obj_set_width(ui_headerCO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerCO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headerCO1, 0);
    lv_obj_set_y(ui_headerCO1, -12);
    lv_obj_set_align(ui_headerCO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_headerCO1, "CO");
    lv_obj_set_style_text_font(ui_headerCO1, &ui_font_weatherText, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_headerCO1, lv_color_hex(0x0C6D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerCO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerCO1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_headerCO1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONumber1 = lv_label_create(ui_panelCO1);
    lv_obj_set_width(ui_CONumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CONumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CONumber1, 0);
    lv_obj_set_y(ui_CONumber1, 10);
    lv_obj_set_align(ui_CONumber1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_CONumber1, "8.4 --/--");

    ui_Time1 = lv_obj_create(ui_tempatureDisplay2);
    lv_obj_set_width(ui_Time1, 118);
    lv_obj_set_height(ui_Time1, 72);
    lv_obj_set_x(ui_Time1, 43);
    lv_obj_set_y(ui_Time1, -95);
    lv_obj_set_align(ui_Time1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Time1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Time1, lv_color_hex(0xEDF3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Time1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Time1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayOfWeek2 = lv_label_create(ui_Time1);
    lv_obj_set_width(ui_dayOfWeek2, 107);
    lv_obj_set_height(ui_dayOfWeek2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayOfWeek2, 1);
    lv_obj_set_y(ui_dayOfWeek2, -15);
    lv_obj_set_align(ui_dayOfWeek2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_dayOfWeek2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_dayOfWeek2, "Wednesday");
    lv_obj_set_style_text_align(ui_dayOfWeek2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayOfWeek2, &ui_font_interTempHeader, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1 = lv_label_create(ui_Time1);
    lv_obj_set_width(ui_day1, 109);
    lv_obj_set_height(ui_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1, -12);
    lv_obj_set_y(ui_day1, 15);
    lv_obj_set_align(ui_day1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_day1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_day1, "14 December");
    lv_obj_set_style_text_align(ui_day1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_tempatureDisplay2);
    lv_img_set_src(ui_Image4, &ui_img_roomtemp_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image4, -45);
    lv_obj_set_y(ui_Image4, -111);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 180);
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tempatureScreen, ui_event_tempatureScreen, LV_EVENT_ALL, NULL);
    uic_tempatureScreen = ui_tempatureScreen;
    uic_tempIndoor1 = ui_tempIndoor1;
    uic_cityNameTemp = ui_cityNameTemp;
    uic_tempOutdoor1 = ui_tempOutdoor1;
    uic_description1 = ui_description1;
    uic_percent1 = ui_percent1;
    uic_AQInumber1 = ui_AQInumber1;
    uic_headerPM25 = ui_headerPM25;
    uic_pm25Number1 = ui_pm25Number1;
    uic_headerPM10 = ui_headerPM10;
    uic_pm10Number1 = ui_pm10Number1;
    uic_headerNO1 = ui_headerNO1;
    uic_NONumber1 = ui_NONumber1;
    uic_headerCO1 = ui_headerCO1;
    uic_CONumber1 = ui_CONumber1;
    uic_dayOfWeek2 = ui_dayOfWeek2;
    uic_day1 = ui_day1;

}

void ui_tempatureScreen_screen_destroy(void)
{
    if(ui_tempatureScreen) lv_obj_del(ui_tempatureScreen);

    // NULL screen variables
    uic_tempatureScreen = NULL;
    ui_tempatureScreen = NULL;
    ui_tempatureDisplay2 = NULL;
    ui_displayTemp1 = NULL;
    ui_indoor1 = NULL;
    uic_tempIndoor1 = NULL;
    ui_tempIndoor1 = NULL;
    ui_IndoorIcon1 = NULL;
    ui_PanelOutdoor1 = NULL;
    uic_cityNameTemp = NULL;
    ui_cityNameTemp = NULL;
    uic_tempOutdoor1 = NULL;
    ui_tempOutdoor1 = NULL;
    ui_panelDayMonth1 = NULL;
    ui_decsIcon1 = NULL;
    uic_description1 = NULL;
    ui_description1 = NULL;
    ui_contHumAQI1 = NULL;
    ui_Hum1 = NULL;
    uic_percent1 = NULL;
    ui_percent1 = NULL;
    ui_headerHum1 = NULL;
    ui_humIcon1 = NULL;
    ui_AQI1 = NULL;
    uic_AQInumber1 = NULL;
    ui_AQInumber1 = NULL;
    ui_headerAQI1 = NULL;
    ui_airIcon1 = NULL;
    ui_contAQIProperties1 = NULL;
    ui_panelPM1 = NULL;
    uic_headerPM25 = NULL;
    ui_headerPM25 = NULL;
    uic_pm25Number1 = NULL;
    ui_pm25Number1 = NULL;
    ui_panelPM2 = NULL;
    uic_headerPM10 = NULL;
    ui_headerPM10 = NULL;
    uic_pm10Number1 = NULL;
    ui_pm10Number1 = NULL;
    ui_panelNO1 = NULL;
    uic_headerNO1 = NULL;
    ui_headerNO1 = NULL;
    uic_NONumber1 = NULL;
    ui_NONumber1 = NULL;
    ui_panelCO1 = NULL;
    uic_headerCO1 = NULL;
    ui_headerCO1 = NULL;
    uic_CONumber1 = NULL;
    ui_CONumber1 = NULL;
    ui_Time1 = NULL;
    uic_dayOfWeek2 = NULL;
    ui_dayOfWeek2 = NULL;
    uic_day1 = NULL;
    ui_day1 = NULL;
    ui_Image4 = NULL;

}
