// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IOTSmartClock

#ifndef UI_TEMPATURESCREEN_H
#define UI_TEMPATURESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tempatureScreen
extern void ui_tempatureScreen_screen_init(void);
extern void ui_tempatureScreen_screen_destroy(void);
extern void ui_event_tempatureScreen(lv_event_t * e);
extern lv_obj_t * ui_tempatureScreen;
extern lv_obj_t * ui_tempatureDisplay2;
extern lv_obj_t * ui_displayTemp1;
extern lv_obj_t * ui_indoor1;
extern lv_obj_t * ui_tempIndoor1;
extern lv_obj_t * ui_IndoorIcon1;
extern lv_obj_t * ui_PanelOutdoor1;
extern lv_obj_t * ui_cityNameTemp;
extern lv_obj_t * ui_tempOutdoor1;
extern lv_obj_t * ui_panelDayMonth1;
extern lv_obj_t * ui_decsIcon1;
extern lv_obj_t * ui_description1;
extern lv_obj_t * ui_contHumAQI1;
extern lv_obj_t * ui_Hum1;
extern lv_obj_t * ui_percent1;
extern lv_obj_t * ui_headerHum1;
extern lv_obj_t * ui_humIcon1;
extern lv_obj_t * ui_AQI1;
extern lv_obj_t * ui_AQInumber1;
extern lv_obj_t * ui_headerAQI1;
extern lv_obj_t * ui_airIcon1;
extern lv_obj_t * ui_contAQIProperties1;
extern lv_obj_t * ui_panelPM1;
extern lv_obj_t * ui_headerPM25;
extern lv_obj_t * ui_pm25Number1;
extern lv_obj_t * ui_panelPM2;
extern lv_obj_t * ui_headerPM10;
extern lv_obj_t * ui_pm10Number1;
extern lv_obj_t * ui_panelNO1;
extern lv_obj_t * ui_headerNO1;
extern lv_obj_t * ui_NONumber1;
extern lv_obj_t * ui_panelCO1;
extern lv_obj_t * ui_headerCO1;
extern lv_obj_t * ui_CONumber1;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_dayOfWeek2;
extern lv_obj_t * ui_day1;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_tempatureScreen;
extern lv_obj_t * uic_tempIndoor1;
extern lv_obj_t * uic_cityNameTemp;
extern lv_obj_t * uic_tempOutdoor1;
extern lv_obj_t * uic_description1;
extern lv_obj_t * uic_percent1;
extern lv_obj_t * uic_AQInumber1;
extern lv_obj_t * uic_headerPM25;
extern lv_obj_t * uic_pm25Number1;
extern lv_obj_t * uic_headerPM10;
extern lv_obj_t * uic_pm10Number1;
extern lv_obj_t * uic_headerNO1;
extern lv_obj_t * uic_NONumber1;
extern lv_obj_t * uic_headerCO1;
extern lv_obj_t * uic_CONumber1;
extern lv_obj_t * uic_dayOfWeek2;
extern lv_obj_t * uic_day1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

